//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNNAPI.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DNN8Entities : DbContext
    {
        public DNN8Entities()
            : base("name=DNN8Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbl_Lookup_QPP_Measure_Type> tbl_Lookup_QPP_Measure_Type { get; set; }
        public DbSet<tbl_Lookup_QPP_Modality> tbl_Lookup_QPP_Modality { get; set; }
        public DbSet<tbl_Lookup_Registry> tbl_Lookup_Registry { get; set; }
        public DbSet<tbl_Lookup_Specialty> tbl_Lookup_Specialty { get; set; }
        public DbSet<tbl_Measure_To_QPP_Modality> tbl_Measure_To_QPP_Modality { get; set; }
        public DbSet<tbl_Lookup_QPP_Measures> tbl_Lookup_QPP_Measures { get; set; }
        public DbSet<vw_QPPMeasures_With_Modality> vw_QPPMeasures_With_Modality { get; set; }
    }
}
